directories:
  output: release
  buildResources: build
appId: com.irrigis.admin
productName: IrriGIS Admin
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - build/**/*
      - public/**/*
      - package.json
extraResources:
  - from: .env
    to: .env
mac:
  target:
    - dmg
    - zip
  category: public.app-category.utilities
win:
  target:
    - nsis
    - portable
  icon: build/icon.png
  verifyUpdateCodeSignature: false
linux:
  target:
    - AppImage
    - deb
  category: Utility
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 33.4.11
